### ISSUE TITLE
Which version supports local filesystem as store + build support

### ISSUE THREAD

**Issue by FilipJanitor** [BTrDB/btrdb-server#57]
Hello, I am working on single node installation and I would like to build from source and use local filesystem as store. I managed to build and run the database but apparently the file storage engine is no longer supported.

So my question is - which version should I use in this case?

I also tried building what is in branches v4dev and v3 as it seems like there is still the local filesystem support, but I was unable to build. There are some package dependencies I don't have, and I am not sure, how to systematically obtain them (namely for example go-bindata-assetfs - is there a way how to systematically obtain them instead of manual resolution?)

Thanks a lot for help

**Comment by immesys** [comment]
Even for a single node installation, we now recommend ceph as it provides a robust way to spread data across multiple hard drives with redundancy.

If you are looking for something easier than that, take a look at https://github.com/BTrDB/smartgridstore/tree/master/devmachine which is a set of scripts for running BTrDB on a single machine easily. It uses ceph still, but backed by a directory of files. By default the environment file uses ephemeral storage so that it runs on Mac, but if you set that to false, the data should persist across container restarts.

There have been so many features added to v4 that I would not recommend using v3 anymore, but if you do want to use v3 let me know and I can go and make sure all the dependencies it uses reference existing repositories. I noticed something bad happened to go-bindata-assetfs at one point so I would have to find a replacement.

**Comment by FilipJanitor** [comment]
Thanks for suggestions! It seems I will try to setup Ceph after all and use
the most recent version.

You mentioned that a big set of features have been added since the v3. I am
particularly interested in the time partitionend tree concept you are
using. Are there any major changes in it, the TS data abstraction or the
underlying data storage logic which have been added since publishing the
usenix paper and thus are not mentioned in it please?
